# Generated by Django 4.1.7 on 2023-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_purchasehistory_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='tickets_bought',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество купленных билетов'),
        ),
    ]
