# Generated by Django 4.1.7 on 2023-05-20 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_alter_movie_rating'),
        ('cinemas', '0002_alter_cinema_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена взрослого билета')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена детского билета')),
                ('price_student', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена студенческого билета')),
                ('price_vip', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена VIP билета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_showtimes', to='cinemas.cinema', verbose_name='Кинотеатр')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_showtimes', to='movies.movie', verbose_name='Фильм')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_showtimes', to='cinemas.room', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price_age', models.CharField(choices=[('Взрослый', 'Adult'), ('Детский', 'Child'), ('Студенческий', 'Student')], max_length=20, verbose_name='Ценовой возраст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_tickets', to='cinemas.seat', verbose_name='Место')),
                ('showtime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime_tickets', to='showtimes.showtime', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ('-created_at',),
            },
        ),
    ]
