# Generated by Django 4.1.7 on 2023-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='price_vip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена VIP билета'),
        ),
    ]
