# Generated by Django 4.1.7 on 2023-05-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showtimes', '0002_alter_showtime_price_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Бронь', 'Reserved'), ('Куплено', 'Bought'), ('Возвращено', 'Returned')], max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
