# Generated by Django 4.1.7 on 2023-05-23 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showtimes', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Бронь', 'Reserved'), ('Куплено', 'Bought'), ('Возвращено', 'Returned')], default='Бронь', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
