# Generated by Django 4.1.7 on 2023-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0006_alter_ticket_status_alter_ticket_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price_age',
            field=models.CharField(choices=[('Adult', 'Взрослый'), ('Child', 'Детский'), ('Student', 'Студенческий')], max_length=20, verbose_name='Ценовой возраст'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Бронь'), ('Child', 'Куплено'), ('Returned', 'Возвращено')], default='Бронь', max_length=50, verbose_name='Статус'),
        ),
    ]
