# Generated by Django 4.1.7 on 2023-05-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0009_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price_age',
            field=models.CharField(choices=[('Взрослый', 'Adult'), ('Детский', 'Child'), ('Студенческий', 'Student'), ('Вип', 'Vip')], max_length=20, verbose_name='Ценовой возраст'),
        ),
    ]
