# Generated by Django 4.1.7 on 2023-05-28 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showtimes', '0010_alter_ticket_price_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('discount_used', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма использованных бонусов')),
                ('discount_added', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма дополненных бонусов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to='showtimes.ticket', verbose_name='Пользователь')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'Истории покупок',
                'ordering': ('-created_at',),
            },
        ),
    ]
