# Generated by Django 4.1.7 on 2023-05-14 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(choices=[('Алматы', 'Almaty'), ('Астана', 'Astana'), ('Шымкент', 'Shymkent'), ('Караганды', 'Karaganda')], max_length=50, verbose_name='Город')),
                ('schedule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расписание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Название зала')),
                ('place_count', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('row_count', models.PositiveSmallIntegerField(verbose_name='Количество рядов')),
                ('seat_count', models.PositiveSmallIntegerField(verbose_name='Количество мест в ряде')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_rooms', to='cinemas.cinema', verbose_name='Кинотеатр')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ряд')),
                ('seat', models.PositiveSmallIntegerField(verbose_name='Номер кресла в ряду')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Вип место')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_seats', to='cinemas.room', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('-created_at',),
            },
        ),
    ]
