# Generated by Django 4.1.7 on 2023-05-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_alter_cinema_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='room',
            name='place_count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мест в ряде'),
        ),
        migrations.AlterField(
            model_name='room',
            name='seat_count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество мест'),
        ),
    ]
