# Generated by Django 4.1.7 on 2023-05-20 12:05

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('adventure', 'Adventure'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('fantasy', 'Fantasy')], max_length=120, verbose_name='Жанр')),
                ('age_rate', models.PositiveSmallIntegerField(verbose_name='Возрастное ограничение')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('-created_at',),
            },
        ),
    ]
