# Generated by Django 4.1.7 on 2023-05-21 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 13)),
            preserve_default=False,
        ),
    ]
