# Generated by Django 4.1.7 on 2023-05-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_end_date_movie_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateTimeField(verbose_name='Конец проката'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateTimeField(verbose_name='Начало проката'),
        ),
    ]
