# Generated by Django 4.1.7 on 2023-05-23 18:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('adventure', 'Приключения'), ('romance', 'Романтика'), ('thriller', 'Триллер'), ('fantasy', 'Фантастика'), ('drama', 'Драма'), ('Horror', 'Ужасы')], max_length=120, verbose_name='Жанр'),
        ),
    ]
